#!/usr/bin/env bash

set -Eeu
set -o pipefail dotglob nullglob failglob

# Environments
{
  cd -- "$(dirname -- "$0")/.."
  GIT_REPO="${GIT_REPO:-"$(basename -- "$PWD")"}"
  GIT_TAG="$(git describe --tags --abbrev=0)"
  VERSION="${GIT_TAG#v}"
  NAME_PREFIX="${GIT_REPO}_${VERSION}"
  MANIFEST="${NAME_PREFIX}_manifest.json"
  DIST="$PWD/dist"
  SHAFILE="$DIST/${NAME_PREFIX}_SHA256SUMS"
  SIGFILE="$SHAFILE.sig"
}

# Import GPG Key
if [[ -n ${GPG_SIGNING_PASSWORD:-""} ]] && [[ -n ${GPG_SIGNING_KEY:-""} ]]; then
  printenv -- GPG_SIGNING_KEY | gpg --batch --passphrase-fd 3 --import 3<<< "$GPG_SIGNING_PASSWORD"
elif [[ -n ${CI:-""} ]]; then
  printf -- '%s\n' "GPG_SIGNING_PASSWORD, GPG_SIGNING_KEY must be set" >&2
  exit 1
fi

# Build Artifacts
{
  SKIP=(--skip publish)
  if [[ -z ${CI:-""} ]]; then
    SKIP+=(--skip validate)
  fi

  GORELEASER_CURRENT_TAG="$GIT_TAG" goreleaser release --clean "${SKIP[@]}"
}

# Generate Checksum
{
  cp -v -- ./terraform-registry-manifest.json "$DIST/$MANIFEST"
  pushd -- "$DIST" > /dev/null
  sha256sum -- "$MANIFEST" *.zip | tee -- "$SHAFILE" >&2
  popd > /dev/null
}

# Generate Signature
{
  GPG_FINGERPRINT="${GPG_FINGERPRINT:-"$(gpg --batch --list-keys --with-colons | awk -F : -- '/^pub:/ { getline; print $10 }' | tail -1)"}"
  gpg --batch --pinentry-mode loopback --passphrase-fd 0 --detach-sign --local-user "$GPG_FINGERPRINT" --output "$SIGFILE" -- "$SHAFILE" <<< "${GPG_SIGNING_PASSWORD:-""}"
}

# Publish Release
if [[ -n ${CI:-""} ]]; then
  gh release upload --clobber -- "$GIT_TAG" "$DIST/$MANIFEST" "$SHAFILE" "$SIGFILE" "$DIST/"*.zip
  gh release edit --draft=false -- "$GIT_TAG"
fi
