---
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0

      - env:
          GH_TOKEN: ${{ github.token }}
        run: |-
          git describe --tags --abbrev=0 | tee -- /dev/stderr | xargs -r -- gh release create --draft=true --
