---
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0

      - env:
          GH_TOKEN: ${{ github.token }}
          GH_USER: ${{ github.actor }}
        run: |-
          # git config --global user.email -- 
          git config --global user.name -- "$GH_USER"
          TAG="$(git describe --tags --abbrev=0)"
          gh release create -- "$TAG"
          git tag --message '' -- "_$TAG"
