---
name: Publish Draft Release with Binaries

on:
  release:
    types: [prereleased]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0

      - uses: actions/setup-go@v5

      - uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      - env:
          GH_TOKEN: ${{ github.token }}
          GIT_REF: ${{ github.ref }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
        run: |-
          GIT_TAG="$(basename -- "$GIT_REF")"
          export -- GIT_TAG
          printenv -- GIT_TAG
          ./scripts/publish
