---
name: Publish Draft Release with Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - "_v*"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0

      - env:
          TAG: ${{ github.ref }}
        run: |-
          git tag --delete -- "$TAG"
          git push --tags

      - uses: actions/setup-go@v5

      - uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true

      - env:
          GH_TOKEN: ${{ github.token }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
        run: |-
          ./scripts/publish
